#!/bin/bash

PROGRAM=arm-none-eabi-gdb
COMMAND_FILE=${COMMAND_FILE:-configs/nrf52832_dk/scripts/arm-gdb.init}
IMAGE=nuttx

#
# Make sure all other runs of this debugger are killed off.
#
clear_hung_debuggers()
{
    if ps -ef | grep ${PROGRAM} >/dev/null; then
        echo "Killing all other ${PROGRAM} programs"
        killall ${PROGRAM} >/dev/null 2>&1
    else
        echo "No other versions of ${PROGRAM} running."
    fi
}

find_nuttx()
{
    local rval=0
    local DPATH=./

    while [ ! -f ${DPATH}"${IMAGE}" ] ; do
        DPATH="../"${DPATH}
        if [ -d "$DPATH"/dev ] ; then
            echo "Reached the top level dir." >&2
            rval=-1
            break
        fi
    done

    echo $DPATH
    return $rval
}

clear_hung_debuggers

DIR=$(find_nuttx)
if [ $? -ne 0 ] ; then
	echo "Failed to find nuttx." >&2
	exit -1
fi

pushd ${DIR} >/dev/null

exec $PROGRAM --command=$COMMAND_FILE $IMAGE

popd >/dev/null

exit
